Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from todo import views
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/',include('blog.urls')),
    path('generator/',include('generator.urls'),name='generator'),
    path('todo/',include('todo.urls'),name='todo'),
    path('horses/',views.horses,name='horses'),
    path('horses/',views.cats,name='cats'),
    path('horses/',views.dogs,name='dogs'),
    path('horses/',views.rescues,name='rescues'),
    path('projects/',views.projects,name='projects'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

portfolio/models.py
from django.db import models

# Create your models here -- classes

class Project(models.Model):
    #Check Django documenations on Field
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    internalurl = models.CharField(max_length=100,blank=True)
    github = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request,'portfolio/home.html', {'projects':projects})

def back(request):
    previous = request.POST.get('previous', '/')
    return redirect(previous)

def horses(request):
    return render(request,'portfolio/horses.html')

def dogs(request):
    return render(request,'portfolio/dogs.html')

def cats(request):
    return render(request,'portfolio/cats.html')

def rescues(request):
    return render(request,'portfolio/rescues.html')

def projects(request):
    return render(request,'portfolio/projects.html')

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/LogoRiders.png" %}">

  <title>Celia Blacu</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/LogoRiders.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Celia's Logo">
        <span>Celia Blacu</span>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <div class="input-group mb-3">
            <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Projects</button>
            <ul class="dropdown-menu">
              {% for project in projects %}
                <li><a class="dropdown-item" href="{{ project.internalurl }}" target="_parent">
                   {{ project.title }}
                  <img src="{{ project.image.url }}" class="img-fluid mb-2" width="25" height="25">

                </a></li>
              {% endfor %}
            </ul>
          </div>

          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}" target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/celia-blacu-519b4b44/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/cblacu" target="_blank">Twitter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:all_blogs' %}" target="_parent">Blog</a>
          </li>

        <div class="input-group mb-3">
          <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">GitHub</button>
          <ul class="dropdown-menu">
            {% for project in projects %}
              <li><a class="dropdown-item" href="{{ project.github }}" target="_blank">{{ project.title }}
                  <img src="{{ project.image.url }}" class="img-fluid mb-2" width="25" height="25">
              </a></li>
            {% endfor %}
          </ul>
        </div>

        <div class="input-group mb-3">
          <button class="btn btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Pets</button>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'horses' %}" target="_parent">Horses</a></li>
              <li><a class="dropdown-item" href="#" target="_parent">Dogs</a></li>
              <li><a class="dropdown-item" href="#" target="_parent">Cats</a></li>
              <li><a class="dropdown-item" href="#" target="_parent">Recues</a></li>
          </ul>
        </div>

        <div class="input-group mb-3">
          <button class="btn btn-outline-warning dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Partners</button>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="https://dmd-concept.ro/" target="_blank">
                DMD Concept
                <img src="{% static 'portfolio/logo-simbol-dmd-concept.jpg' %}" class="img-fluid mb-2" width="25" height="25">
              </a></li>
              <li><a class="dropdown-item" href="https://www.einherzfuerstreuner.de/" target="_blank">A Heart For Strays
                <img src="{% static 'portfolio/Logo-hp.png' %}" class="img-fluid mb-2" width="25" height="25">
              </a></li>
              <li><a class="dropdown-item" href="https://aldocamp.ro/" target="_blank">Aldo Camp
                <img src="{% static 'portfolio/logo-aldo-camp_48px.png' %}" class="img-fluid mb-2" width="25" height="25">
              </a></li>
              <li><a class="dropdown-item" href="http://www.animalia-vet.ro/" target="_blank">Cabinet veterinar Animalia
                <img src="{% static 'portfolio/LOGO-animalia.png' %}" class="img-fluid mb-2" width="25" height="25">
              </a></li>
          </ul>
        </div>


        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/cats.html
{% extends 'portfolio/base.html' %}

{% load static %}

<div class="container">
  {% block content %}
    <h1>Cats</h1>
  {% endblock %}
</div>

portfolio/templates/portfolio/dogs.html
{% extends 'portfolio/base.html' %}

{% load static %}

<div class="container">
  {% block content %}
    <h1>Dogs</h1>
  {% endblock %}
</div>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<input type="hidden" name="previous" value="{{ request.path }}">

  <section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Hi, I'm Celia.</h1>
    <p class="lead text-muted">Hey, my name is Celia Blacu, am a software developer and, as a hobby, proud owner of a few pets.<br>
      I am also an equestrian and involved in pet rescue.
    </p>
    <p>
      <a href="mailto:celia.blacu@gmail.com" class="btn btn-primary my-2">Email Me</a>
    </p>
    <img src="{% static 'portfolio/Celia.jpg' %}" height="300" />
  </div>
</section>

<!--
  <h2 class="mt-5">Projects</h2>
  <hr>
  <div class="row">

    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

      {% if project.url %}
      <a href="{{ project.internalurl }}" target="_blank">
        <img src="{{ project.image.url }}" class="img-fluid mb-2">
      </a>
      {% else %}

      <img src="{{ project.image.url }}" class="img-fluid mb-2" width="200" height="200">
      {% endif %}
      <h3>{{ project.title }}</h3>
      <p>{{ project.description }}</p>

    </div>

    {% endfor %}
  </div>

  -->

{% endblock %}

portfolio/templates/portfolio/horses.html
{% extends 'portfolio/base.html' %}

{% load static %}

<div class="container">
  {% block content %}

  <div align="center">
    <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTVJVH8jJCWbB87KPQOrVgCHMBc9hHSrqpJwjmAUzc_Tuxh8MVPyruQIPitKGaAMQ/embed?start=true&loop=false&delayms=2000"
    frameborder="1" width="640" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
    <br>
  </div>

    <h2 class="mt-5">Competitions</h2>
    <hr>
    <div class="row">

<!--
      <div class="col-lg-4 col-md-6">
        <h5>Endurance Competitions</h5>

      </div>
      </div>
    -->
    <div class="col-lg-6 col-md-6">
      <h5>Endurance</h5>
        <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vT3uSFwnTzh_CzfXzWbiHhnYfeTxMeCtUJs-c7M2mTRUdQKhszFogXmIPn_RoHjOmwgt1XqelonPEME/embed?start=true&loop=false&delayms=3000"
        frameborder="1" width="500" height="300" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
    </div>

      <div class="col-lg-6 col-md-6">
        <h5>Show Jumping</h5>
          <iframe width="500" height="300" src="https://www.youtube-nocookie.com/embed/3C9aAMZfNMw" title="YouTube video player"
          frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>

    </div>

    <h2 class="mt-5">Our Trainings</h2>
    <hr>
    <div class="row">

      <div class="col-lg-6 col-md-6"><h5>Endurance</h5>
        <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTXhQJ4_ygXai949gemtorchYKX8IRP43ymoQXL08mzQCP-2fMnaSM4rI5E-pYpkBOasqOSIOjLdqAB/embed?start=true&loop=false&delayms=3000"
        frameborder="1" width="500" height="300" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
        </div>

      <div class="col-lg-6 col-md-6"><h5>Jumping</h5>
          <iframe width="500" height="300" src="https://www.youtube-nocookie.com/embed/_9gVqpplkW4" title="YouTube video player"
          frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>


    </div>
  {% endblock %}
</div>

portfolio/templates/portfolio/projects.html
{% extends 'portfolio/base.html' %}

{% load static %}

<div class="container">
  {% block content %}
    <h1>Projects</h1>
  {% endblock %}
</div>

portfolio/templates/portfolio/rescues.html
{% extends 'portfolio/base.html' %}

{% load static %}

<div class="container">
  {% block content %}
    <h1>Rescues</h1>
  {% endblock %}
</div>