Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from todo import views
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/',include('blog.urls')),
    path('generator/',include('generator.urls'),name='generator'),
    path('todo/',include('todo.urls'),name='todo'),
    path('horses/',views.horses,name='horses'),
    path('horses/',views.cats,name='cats'),
    path('horses/',views.dogs,name='dogs'),
    path('horses/',views.rescues,name='rescues'),
    path('projects/',views.projects,name='projects'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

generator/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = 'generator'

urlpatterns = [
    #path('hithere/', admin.site.urls),
    path ('',views.home,name='home'),
    #path ('generatedpassword/', views.password, name='password'), --this works because name matters
    path ('password/', views.password, name='password'),
    path('about/',views.about, name='about'),
    path('back/',views.back, name='back')
]

generator/models.py
from django.db import models

# Create your models here.

generator/views.py
from django.shortcuts import render
from django.http import HttpResponse
import random
from django.shortcuts import redirect
# Create your views here.

def home(request):
    #return HttpResponse('Hello there')

    #render - function from Django that allows you to pass back
    #a template that turns evetually into an HTTP HttpResponse
    return render(request,'generator/home.html')

def password(request):

    characters = list('abcdefghijklmnopqrstuvwxyz')
    if request.GET.get('uppercase'):
        characters.extend(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'))
    if request.GET.get('special'):
        characters.extend(list('~!@#$%^&*()_+-=?'))
    if request.GET.get('numbers'):
        characters.extend(list('0123456789'))
    length = int(request.GET.get('length','12'))

    thepassword = ''
    for x in range(length):
        thepassword += random.choice(characters)

    return render(request,'generator/password.html',{'password':thepassword})

def about(request):
    return render(request,'generator/about.html')

def back(request):
    previous = request.POST.get('previous', '/')
    return redirect(previous)

generator/templates/generator/about.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

<div class="container text-center">
  <h2>About page</h2>
  <p>Author: <i>Celia Blacu</i></p>
  <p>Email: <i>celia.blacu@gmail.com</i></p>
  <a href=" {% url 'generator:home' %} " class="btn btn-warning">Home</a>
</div>

generator/templates/generator/home.html
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

<div class="container text-center">

<img src="{% static 'generator/pass_gen.png' %}" height="200" />
<h2>Password Generator</h2>

<form action="{% url 'generator:password' %}">
  <select name="length">
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
    <option value="11">11</option>
    <option value="12" selected="selected">12</option>
    <option value="13">13</option>
    <option value="14">14</option>
  </select>  Length

  <br>
  <input type="checkbox" name="uppercase"> Uppercase</input>
  <br>
  <input type="checkbox" name="numbers"> Numbers</input>
  <br>
  <input type="checkbox" name="special"> Special Characters</input>
  <br>
  <input type="submit" value="Generate password" class="btn btn-warning">
  </input>

  <input type="hidden" name="previous" value="{{ request.path }}">

</form>
<a href=" {% url 'generator:about' %} " class="btn btn-warning">About</a>
<a href=" {% url 'generator:back' %} " class="btn btn-primary">Back</a>
</div>

generator/templates/generator/password.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

<div class="container text-center">
  <h1>Your password is:</h1>
  <h2 class="alert alert-success">{{ password }}</h2>
  <a href=" {% url 'generator:home' %} " class="btn btn-warning">Home</a>
  <a href=" {% url 'generator:password' %} " class="btn btn-warning">Refresh</a>
</div>