Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from todo import views
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/',include('blog.urls')),
    path('generator/',include('generator.urls'),name='generator'),
    path('todo/',include('todo.urls'),name='todo'),
    path('horses/',views.horses,name='horses'),
    path('horses/',views.cats,name='cats'),
    path('horses/',views.dogs,name='dogs'),
    path('horses/',views.rescues,name='rescues'),
    path('projects/',views.projects,name='projects'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    #Check Django documenations on Field
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    #blog_count = Blog.objects.count
    blogs = Blog.objects.order_by('-date') #[:5] to get the first 5 items
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request,blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Celia has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>

    <! ––
    safe - to interpret the html tags
    striptags - to ignore the html tags without interpreting them
    ––>

  {% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

  <h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

  <h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

  {{ blog.description|safe }}
  
{% endblock %}