Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from todo import views
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/',include('blog.urls')),
    path('generator/',include('generator.urls'),name='generator'),
    path('todo/',include('todo.urls'),name='todo'),
    path('horses/',views.horses,name='horses'),
    path('horses/',views.cats,name='cats'),
    path('horses/',views.dogs,name='dogs'),
    path('horses/',views.rescues,name='rescues'),
    path('projects/',views.projects,name='projects'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

generator/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = 'generator'

urlpatterns = [
    #path('hithere/', admin.site.urls),
    path ('',views.home,name='home'),
    #path ('generatedpassword/', views.password, name='password'), --this works because name matters
    path ('password/', views.password, name='password'),
    path('about/',views.about, name='about'),
    path('back/',views.back, name='back')
]

todo/urls.py
from django.contrib import admin
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    #Authentication
    path('signup/',views.signupuser,name='signupuser'),
    path('logout/',views.logoutuser,name='logoutuser'),
    path('login/',views.loginuser,name='loginuser'),

    #Todos
    path('create/',views.createtodo,name='createtodo'),
    path('current/',views.currenttodos,name='currenttodos'),
    path('todo/<int:todo_pk>',views.viewtodo,name='viewtodo'),
    path('todo/<int:todo_pk>/complete',views.completetodo,name='completetodo'),
    path('todo/<int:todo_pk>/delete',views.deletetodo,name='deletetodo'),
    path('completed/',views.completedtodos,name='completedtodos'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True,blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

def __str__(self):
    return self.title

todo/forms.py
from django.forms import ModelForm
from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title','memo','important']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import TodoForm
from .models import Todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

#--------------------------------------------------------
# HOME
#-------------------------------------------------------
def home(request):
    return render(request,'todo/home.html')

def signupuser(request):
    if request.method == 'GET':
        return render(request,'todo/signupuser.html',{'form':UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            # Create a new user
            try:
                user = User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('todo:currenttodos')
            except IntegrityError:
                return render(request,'todo/signupuser.html',{'form':UserCreationForm(),'error':'This username has already been taken. Please choose another one.'})
        else:
            # Tell the user passwords dont match
            return render(request,'todo/signupuser.html',{'form':UserCreationForm(),'error':'Passwords did not match'})

#--------------------------------------------------------
# LOGOUT
#-------------------------------------------------------
@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

#--------------------------------------------------------
# LOGIN
#-------------------------------------------------------
def loginuser(request):
    if request.method == 'GET':
        return render(request,'todo/loginuser.html',{'form':AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request,'todo/loginuser.html',{'form':AuthenticationForm(),'error':'Username and password did not match'})
        else:
            login(request, user)
            return redirect('todo:currenttodos')

#--------------------------------------------------------
# CREATE TODOs
#-------------------------------------------------------
@login_required
def createtodo(request):
    if request.method == 'GET':
        return render(request,'todo/createtodo.html',{'form':TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request,'todo/createtodo.html',{'form':TodoForm(),'error':'Incorrect data passed in. Please try again.'})

#--------------------------------------------------------
# CURRENT TODOs
#-------------------------------------------------------
@login_required
def currenttodos(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=True)
    return render(request,'todo/currenttodos.html', {'todos':todos})

#--------------------------------------------------------
# VIEW AND UPDATE TODO
#-------------------------------------------------------
@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request,'todo/viewtodo.html', {'todo':todo,'form':form})
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request,'todo/viewtodo.html', {'todo':todo,'form':form,'error':'Incorrect data passed in. Please try again.'})

#--------------------------------------------------------
# COMPLETE TODO
#-------------------------------------------------------
@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('todo:currenttodos')

#--------------------------------------------------------
# DELETE TODO
#-------------------------------------------------------
@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:currenttodos')

#--------------------------------------------------------
# COMPLETED TODOs
#-------------------------------------------------------
@login_required
def completedtodos(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request,'todo/completedtodos.html', {'todos':todos})

def back(request):
    previous = request.POST.get('previous', '/')
    return redirect(previous)

todo/templates/todo/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="icon" type="image/png"  href="{% static 'todo/logo.png' %}">

    <title>Celia's TODO Application</title>
</head>
<body>


<nav class="navbar navbar-expand-md navbar-light bg-info">
<div class="container">
    <a class="navbar-brand" href="{% url 'generator:back' %}">
        <img src="{% static 'todo/logo.png' %}" width="30" height="30" class="d-inline-block align-top">

    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">

                <li class="nav-item {{ current }}">
                    <a class="nav-link" href="{% url 'todo:currenttodos' %}">Current</a>
                </li>
                <li class="nav-item {{ completed }}">
                    <a class="nav-link" href="{% url 'todo:completedtodos' %}">Completed</a>
                </li>
                <li class="nav-item {{ create }}">
                    <a class="nav-link" href="{% url 'todo:createtodo' %}">Create</a>
                </li>

        </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                    <form style='display: none;' method="POST" action="{% url 'todo:logoutuser' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit" class="btn btn-info">Logout</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:signupuser' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:loginuser' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/todo/completedtodos.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <h1>Completed Todos</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <div class="list-group">
                {% for todo in todos %}
                    <a href="{% url 'todo:viewtodo' todo.id %}"
                      class="list-group-item list-group-item-action{% if todo.important %} list-group-item-warning{% endif %}">
                      <b>{{ todo.title }}</b> - {{ todo.datecompleted|date:'M j Y H:i' }}
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/createtodo.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Todo</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title"><b>Title</b></label>
                    <input type="text" name="title" class="form-control" id="title" required>
                </div>
                <div class="form-group">
                    <label for="memo"><b>Memo</b></label>
                    <textarea name="memo" class="form-control" id="memo" ></textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="important" class="form-check-input" id="important">
                    <label class="form-check-label" for="important"><b>Important</b></label>
                </div>
                <button type="submit" class="btn btn-info">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

todo/templates/todo/currenttodos.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% if todos %}
                 <h1>You have {{ todos.count }} Outstanding Todo {{ todos.count|pluralize }}</h1>
            {% else %}
                           <h1>Current Todos</h1>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
        {% if todos %}
            <div class="list-group">
                {% for todo in todos %}
                    <a href="{% url 'todo:viewtodo' todo.id %}"
                      class="list-group-item list-group-item-action{% if todo.important %} list-group-item-warning{% endif %}">
                      <b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }}{% endif %}
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-center">
                <h2>It looks like you don't have any outstanding todo-es! Nice work.</h2>
            <br>
            <a role="button" class="btn btn-info" href="{% url 'todo:createtodo' %}">New Todo</a>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

todo/templates/todo/home.html
{% extends "todo/base.html" %}
{% load static %}
{% block content %}
  <input type="hidden" name="previous" value="{{ request.path }}">
<br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">
          <img src="{% static 'todo/todo.png' %}" height="200" />
          <h1>Welcome to Celia's TODO App!</h1>
          <p>It is time to get you organized!</p>

          <a role="button" class="btn btn-info btn-lg" href="{% url 'todo:signupuser' %}">Start</a>
          <a role="button" class="btn btn-info btn-lg" href="{% url 'generator:back' %}">Back</a>

        </div>
    </div>


{% endblock %}

todo/templates/todo/loginuser.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'todo:signupuser' %}">Sign Up here</a>
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/signupuser.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'todo:loginuser' %}">Login here</a>
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/viewtodo.html
{% extends "todo/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Todo</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title"><b>Title</b></label>
                    <input type="text" name="title" class="form-control" id="title" value="{{ todo.title }}" required>
                </div>
                <div class="form-group">
                    <label for="memo"><b>Memo</b></label>
                    <textarea name="memo" rows="5" class="form-control" id="memo" >{{ todo.memo }}</textarea>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="important" class="form-check-input" id="important" {% if todo.important %}checked{% endif %}>
                    <label class="form-check-label" for="important"><b>Important</b></label>
                </div>
                {% if todo.datecompleted is None %}
                  <button type="submit" class="btn btn-info">Save</button>
                  <button type="button" class="btn btn-success" onclick="$('#complete').click()">Complete</button>
                {% else %}
                  <button type="submit" class="btn btn-info" disabled>Save</button>
                  <button type="button" class="btn btn-success" disabled>Complete</button>
                {% endif %}
                <button type="button" class="btn btn-warning" onclick="$('#delete').click()">Delete</button>
            </form>
        </div>
    </div>
    {% if todo.datecompleted is None %}
        <form style='display: none;' method="POST" action="{% url 'todo:completetodo' todo.id %}">
            {% csrf_token %}
            <button id="complete" type="submit">Complete</button>
        </form>
    {% endif %}
    <form style='display: none;' method="POST" action="{% url 'todo:deletetodo' todo.id %}">
        {% csrf_token %}
        <button id="delete" type="submit">Delete</button>
    </form>
{% endblock %}